apiVersion: apps/v1
kind: Deployment

metadata:
  name: mc-player
  namespace: emortalmc
  labels:
    app: mc-player

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-player

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: mc-player
    spec:
      containers:
        - name: mc-player
          image: ghcr.io/emortalmc/mc-player-service:2b561f45b04cb42428eb994658e3d3b28d4e8b07
          ports:
            - name: grpc
              containerPort: 9010

          env:
            - name: "DEVELOPMENT"
              value: "false"
            - name: KAFKA_HOST
              value: default-kafka-bootstrap
            - name: KAFKA_PORT
              value: "9092"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mc-player-service-db-creds
                  key: connection-string
            - name: PORT
              value: "9010"
