name: ci
on:
  push:

env:
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false
      - uses: actions/checkout@v3
      - name: go-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 2m0s

  go-publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ go-lint ]
    runs-on: ubuntu-latest

    steps:
      - uses: emortalmc/actions/go-single-publish@main
        with:
          registry-password: ${{ secrets.GITHUB_TOKEN }}

  k8s-repo-update:
    needs: [ go-publish ]
    runs-on: ubuntu-latest
    steps:
      - uses: emortalmc/actions/k8s-sync@main
        with:
          ssh-key: ${{ secrets.AUTOMATION_SSH_KEY }}
          docker-image-name: ${{ env.DOCKER_IMAGE_NAME }}
          manifest-path: apis/mc-player.yaml
