name: ci
on:
  push:

env:
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false
      - uses: actions/checkout@v3
      - name: go-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 2m0s

  go-build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ go-lint ]
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-to: type=inline
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.2
      - name: helm lint
        run: helm lint helm

  helm-publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ go-build, helm-lint ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.2
      - name: helm publish
        run: |
          helm registry login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          helm package ./k8s/chart/${{ github.event.repository.name }} --version "1.0.0-${{ github.sha }}" --app-version ${{ github.sha }}
          helm push helm-${{ github.event.repository.name }}-1.0.0-${{ github.sha }}.tgz oci://ghcr.io/${{ github.actor }}
