name: ci
on:
  push:

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: emortalmc/actions/go/lint@main

  go-publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ go-lint ]
    runs-on: ubuntu-latest

    steps:
      - uses: emortalmc/actions/go/publish-single@main
        with:
          registry-password: ${{ secrets.GITHUB_TOKEN }}

  k8s-repo-update:
    needs: [ go-publish ]
    runs-on: ubuntu-latest
    steps:
      - uses: emortalmc/actions/k8s-sync@main
        with:
          ssh-key: ${{ secrets.AUTOMATION_SSH_KEY }}
          docker-image-name: ghcr.io/${{ github.repository }}
          manifest-path: apis/mc-player.yaml
